### PR TITLE
Use Arch's background color in new Vector

### PR DESCRIPTION
**Pull request by nl6720**
- Use Arch's background color in new Vector
- Disable sidebar's gradient in new Vector

### CODE REVIEW

**Review by pierres — APPROVED** [review]
I tested this locally. Looks good. Thank you!

**Comment by nl6720** [comment]
@pierres, could you tag `1.37.1-4` please?

**Comment by pierres** [comment]
@nl6720 Done

**Comment by nl6720** [comment]
Thanks!

**Pull request merged**
