### PR TITLE
Enable the TextExtracts extension

### PR DESCRIPTION
**Pull request by anna328p**
This extension generates short snippets of pages. This is useful for embeds and external applications that query the API.

I learned that this extension was disabled in the process of writing a chat bot to allow users of the unofficial Arch Linux Discord server to search the Arch Wiki. Because the Arch Wiki does not provide text extracts, the bot cannot give any context for a search result other than a title and link. [Code example](https://github.com/arch-community/qbot/blob/master/modules/arch.rb)

Enabling this extension will also allow links to the Arch Wiki on Twitter, Discord, similar websites that use the oEmbed standard to display snippets of pages.

### CODE REVIEW

**Comment by lahwaacz** [comment]
What is the performance impact on the Arch server when using this extension's queries? The [documentation](https://www.mediawiki.org/wiki/Extension:TextExtracts) says there are no database changes, so I assume there is no caching.

**Comment by dkudriavtsev** [comment]
> What is the performance impact on the Arch server when using this extension's queries? The [documentation](https://www.mediawiki.org/wiki/Extension:TextExtracts) says there are no database changes, so I assume there is no caching.

I'm not sure what the performance impact would be. The extension seems to parse wikitext but strip out HTML classes, which shouldn't have much more impact than just loading the page.

It also seems to have its own caching.

Here's the source for the extension: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/TextExtracts/+/refs/heads/master/includes/ApiQueryExtracts.php

**Comment by anna328p** [comment]
I hate to bump issues, but I'm wondering if this issue got overlooked 17 months ago?

**Comment by nl6720** [comment]
After https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/516, `LocalSettings.archlinux.org.php` is not used anymore. The file is now in https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/master/roles/archwiki/templates/LocalSettings.php.j2.

Any changes to it should be submitted to the [infrastructure](https://gitlab.archlinux.org/archlinux/infrastructure) repo.

**Pull request closed without merging**
