### PR TITLE
Update to MediaWiki 1.35.0

### PR DESCRIPTION
**Pull request by lahwaacz**
First two commits just update MediaWiki and the extensions to 1.35.0. For reference, this is what I did for these commits:
```
git clone git@github.com:lahwaacz/archlinux-mediawiki.git --branch master archwiki
git clone https://gerrit.wikimedia.org/r/mediawiki/core.git --branch REL1_35 --depth=1 --recurse-submodules --shallow-submodules mediawiki
rsync -rlptD --exclude={"/.git*",.gitignore,/.travis.yml} --delete mediawiki/ archwiki/
cd archwiki
git checkout -- favicon.ico LocalSettings.archlinux.org.php docker extensions/{ArchLinux,FluxBBAuth}
git checkout -- extensions/{AbuseFilter,BounceHandler,CheckUser,Lockdown,TitleKey,UserMerge}
git add -A
git commit -m "Update to MediaWiki 1.35.0"

git submodule init
git submodule update
for path in extensions/{AbuseFilter,BounceHandler,CheckUser,Lockdown,TitleKey,UserMerge}; do
    git submodule set-branch --branch REL1_35 $path
done
git submodule update --remote
git add -A
git commit -m "Update extensions to 1.35.0"
```

Next follow commits which update the configuration and the ArchLinux extension/skin for the new version. There is an ugly hack to make the Arch navbar appear, because the previous way does not work anymore - see the commit message for details. Maybe @pierres could follow up on this if he can figure out how to fix the extension "properly"?

Also cc @grazzolini, @jelly 

P.S.: Before deploying this, we should merge [this PR to infrastructure](https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/125), otherwise the skin would be completely broken for users until the old assets expire in the cache.

### CODE REVIEW

**Comment by pierres** [comment]
Thanks for looking into the update. Looking into it is already on my todo list; probably wont happen before the weekend though.

**Comment by pierres** [comment]
I'll merge your commits into the mw-1.35 branch and finalize the update there.

**Comment by pierres** [comment]
@lahwaacz  Regarding your comment about the Vector skin hook: I am now injecting the navigation in the raw HTML output. This makes it independent from the skin implementation. I did not found any oter hook we could use :-( https://github.com/archlinux/archwiki/commit/cc77f5c48572a3dd410e8a6e9bed9da8a0a9e457

**Comment by lahwaacz** [comment]
@pierres I agree that modifying the raw HTML output is probably the only way to do it reliably, at least the hack I made to the Vector skin is gone. But your commit https://github.com/archlinux/archwiki/commit/59b830f293f73c5bdc01f1f37d346f5eee7b7420 does not work yet - the `ArchNavBar.php` file which is included in `ArchLinux.hooks.php` uses `$skinTemplate->getTitle()`, but the `skinTemplate` parameter is gone...

**Comment by pierres** [comment]
@lahwaacz  Good catch. My test env did not configure the menu so I did not noticed.
* I included an example menu
* I fixed the title handling

**Comment by lahwaacz** [comment]
Thanks, now it works.

**Pull request merged**
