### PR TITLE
Add DarkMode extension as submodule

### PR DESCRIPTION
**Pull request by lb-wilson**
Add DarkMode toggle. Intended to coincide with https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/664. The other PR for this is stale. My previous PR was automatically closed when I synced my fork. Please let me know if you see any issues, and I will change them right away.

### CODE REVIEW

**Comment by nl6720** [comment]
It doesn't look like it remembers the dark mode setting for logged-out users.

Would be great if would be automatic, i.e. by supporting `prefers-color-scheme`.

**Comment by nl6720** [comment]
archnavbar probably needs to add the [`mw-no-invert`](https://www.mediawiki.org/wiki/Extension:DarkMode#Excluding_elements_from_dark_mode) class to avoid recoloring.

**Comment by lb-wilson** [comment]
> archnavbar needs to add the [`mw-no-invert`](https://www.mediawiki.org/wiki/Extension:DarkMode#Excluding_elements_from_dark_mode) class to avoid recoloring.
> 
> https://github.com/archlinux/archwiki/blob/dc53c8ed5f729e2e1a1e14b506f6e80d85199a42/extensions/ArchLinux/ArchNavBar.php#L13

I'm happy to help however is appropriate, although I'll be a little delayed until after Christmas.

Should I include that change in this PR, create a separate PR, or leave that up to the person(s) leading `archnavbar`?

**Comment by nl6720** [comment]
Include the change to archnavbar in this PR, but in a separate commit.

No worries about being delayed. 🎄

**Comment by nl6720** [comment]
Please rebase to get rid of the "`Merge branch 'archlinux:master' into master`" commit.

**Review by nl6720 — CHANGES_REQUESTED** [review]
Please rebase to get rid of the "`Merge branch 'archlinux:master' into master`" commit.

**Review by nl6720 — APPROVED** [review]

**Review by lahwaacz — APPROVED** [review]

**Comment by nl6720** [comment]
Note to self: the `<p>` in [Template:META Related articles start](https://wiki.archlinux.org/title/Template:META_Related_articles_start) needs to be excluded too.

**Comment by nl6720** [comment]
@pierres, could you merge this?

**Comment by lahwaacz** [comment]
We might need to do some more tweaking for the Arch icon: https://i.postimg.cc/wBkH9m9t/DarkMode.png

This was tested with the [Chrome extension](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj).

**Comment by lahwaacz** [comment]
Should the extension remember if the dark mode is active when the user loads a new page? It does not behave like so on my testing wiki...

**Comment by nl6720** [comment]
It does for logged-in users.

**Comment by nl6720** [comment]
You can add `$wgDefaultUserOptions['darkmode'] = 1;` to `LocalSettings.php` to enable it by default.

**Comment by lahwaacz** [comment]
It does not remember its state even when I log in as LocalUser... Thought it might be due to the browser's anonymous window, but it's still the same in `qutebrowser --temp-basedir`.

**Comment by nl6720** [comment]
Works for me™.
Check the `user_properties` table in the DB.

```mysql
MariaDB [mediawiki]> SELECT * FROM user_properties WHERE up_property = 'darkmode';
+---------+-------------+----------+
| up_user | up_property | up_value |
+---------+-------------+----------+
|       6 | darkmode    | 1        |
|      10 | darkmode    | 1        |
+---------+-------------+----------+
2 rows in set (0,001 sec)
```

**Comment by lahwaacz** [comment]
Hmm, it does not store anything there for me...

**Comment by lahwaacz** [comment]
It might be because MediaWiki or jQuery does not like my URLs (`https://local-archwiki/`) so I don't think this is a blocker, let's see it in production.

**Comment by killertofus** [comment]
in prod it does not save the changes

Uploading 2023-02-03 21-00-57.mp4…

**Comment by nl6720** [comment]
The preference is stored in the database, not a cookie, so it is only remembered for logged-in users.

**Comment by killertofus** [comment]
https://bugs.archlinux.org/task/77389

**Pull request merged**
