### PR TITLE
Move categories under h1 in VectorTemplate.php

### PR DESCRIPTION
**Pull request by Larivact**
See [the relevant ArchWiki discussion](https://wiki.archlinux.org/index.php?title=ArchWiki_talk:Administrators#Patch_Vector_skin_to_display_categories_at_the_top_of_the_page).

### CODE REVIEW

**Comment by Bluewind** [comment]
I'll merge this once [this discussion](https://lists.archlinux.org/pipermail/arch-devops/2018-November/000184.html) is resolved.

**Comment by lahwaacz** [comment]
You might consider merging with `--squash` (or "Squash and merge" on Github), in which case the merge commits will look a lot like those from the tarball method and they won't have the MediaWiki tags.

**Comment by Bluewind** [comment]
Yeah, but then we don't have the history and having that is actually pretty nice for debugging. Thanks for the suggestion though.

**Comment by pierres** [comment]
Imho these changes should be pushed upstream. I don't think forking MediaWiki is a good idea. We should stick to extensions. We did have our own fork and a especially a theme fork in the past which made major update quite painful. Also keeping things vanilla and pushing patches upstream is a core Arch principle and I do not know why this would not apply here.

**Comment by Bluewind** [comment]
> Also keeping things vanilla and pushing patches upstream is a core Arch principle

Fair enough. I won't merge this PR then and I won't change the way our repo looks. Do you think you could convert this into an extension like you did with our other style changes or get upstream to look at the patch?

**Comment by jelly** [comment]
Closed due inactivity and no follow up which led to the creation of an addon.

**Pull request closed without merging**
