### PR TITLE
Use full browser width in new Vector theme

### PR DESCRIPTION
**Pull request by MarcoCLA**

### CODE REVIEW

**Comment by klausenbusk** [comment]
What is the rationale behind this change?

Many thoughts has been put into limiting the content width: https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Limiting_content_width

**Comment by MarcoCLA** [comment]
These considerations are mainly aimed at textual content, not documentation type content like the arch wiki.

Trilby sums is up quite well ([source](https://bbs.archlinux.org/viewtopic.php?pid=2010944#p2010944)):
_There is a good / rational basis for this rule, it's just really misapplied here.  For long prose, or full flowing paragraphs, certain line lengths are much easier to read.  The ideal line length is in the range of 60em for this sort of text.  This is why newspapers and many magazines / journals are laid out in multiple columns, and also why most novels are much smaller (they have a single column, but it may only be 4-5 inches wide).  But that is not the sort of text we have in our wiki.  The wiki is not a novel; it has sections, boxes, and bullet points, and "paragraphs" aren't really meaningful as generally there may only be 1 or 2 sentences together before a break.
So a 60em width for actual paragraphs of text can make sense.  But our wiki doesn't really have paragraphs of text._

[This mediawiki page](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Repository/First_Prototype_Feedback_Report#Why_not_to_choose_%22the_simplest%22_solution) refers to two considerations which have to be taken into account when deciding line lengths. They decide between easy readability (shorter line lengths preferred) and being able to easily skim and search around (longer line lengths preferred).
I think the Arch wiki will benefit more from the second requirement than the first.

**Comment by Joshua-Ashton** [comment]
+1, the new theme is pretty silly on 16:9 -- especially for scripts/code segments.

**Comment by Joshua-Ashton** [comment]
Example of code blocks:

https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF

image

image

The line wrapping is very bad here -- it makes things way less readable, is ambiguous. Code blocks should be scrollables if it can't fit with formatting unchanged.

There are more (and worse) examples across the wiki.

**Comment by lahwaacz** [comment]
> The line wrapping is very bad here -- it makes things way less readable, is ambiguous. Code blocks should be scrollables if it can't fit with formatting unchanged.

That is unrelated to the recent theme change. Line wrapping has been like this for a long time and nobody complained – even those using small screens.

**Comment by Joshua-Ashton** [comment]
So now everyone has to suffer like they had a smaller screen?

gamescope_2021-12-25_21-22-11

And sure, it is technically "unrelated" as it is not a new issue -- but it was less of a problem before, this has simply just amplified the problem and made me aware of it now.

**Comment by LambdAurora** [comment]
> What is the rationale behind this change?
> 
> Many thoughts has been put into limiting the content width: https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Limiting_content_width

I find it a bit ironic that you link a page about limiting content width while that page itself does not limit its width.

Now, let me link this: https://en.wikipedia.org/wiki/Line_length#Electronic_text
>  Researchers have suggested that longer lines are better for quick scanning, while shorter lines are better for accuracy.[3] Longer lines would then be better suited for cases when the information will likely be scanned, while shorter lines would be appropriate when the information is meant to be read thoroughly.

Arch Wiki is not something that someone will thoroughly read from the start to the end. It's a place of technical knowledge which users will quickly scan through to find which information they actually need in their use-case, from the linked Wikipedia page, this use-case describes perfectly "quick scanning" which recommends longer lines. Thus the line width should not be limited.

I found myself having trouble reading through the wiki since the recent introduction of width limit, a rule mostly made for books which is quite nonsensical for this type of wiki imo.

**Comment by otisdog8** [comment]
Does this PR still keep the width limit on mobile? If so I think this is a great idea.

**Comment by LambdAurora** [comment]
> Does this PR still keep the width limit on mobile? If so I think this is a great idea.

There's technically no width limit on mobile with this PR. But from my testing with removing the width limit on mobile is, it's still constrained within the mobile's screen width, so it *should* be fine as-is.

**Pull request closed without merging**
